info:
    title: static
    version: 1.0.0
openapi: 3.1.0
paths:
    /foo/bar:
        post:
            operationId: postFooBar
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    car:
                                        type: string
                                type: object
                            x-static-response: |-
                                {
                                    "car": "dar"
                                }
                    description: Success
